apiVersion: v1
kind: Secret
metadata:
  name: postgres-config
type: Opaque
stringData:
  PG_USER: |-
    {{- if .Values.postgresql.existingSecret.enabled }}
    {{- $secretName := .Values.postgresql.existingSecret.name }}
    {{- $userKey := .Values.postgresql.existingSecret.userKey }}
    {{- $secret := default (dict "data" (dict)) (lookup "v1" "Secret" "argo" "$secretName") }}
    {{- $secretKey := $secret.data.username | b64dec }}
    {{ $secretKey }}
    {{- else }}
    {{ .Values.postgresql.user }}
    {{- end }}
  PG_USER_PASSWORD: |-
    {{- if .Values.postgresql.existingSecret.enabled }}
    {{- $secretName := .Values.postgresql.existingSecret.name }}
    {{- $passwordKey := .Values.postgresql.existingSecret.passwordKey }}
    {{- $secret := default (dict "data" (dict)) (lookup "v1" "Secret" "argo" "$secretName") }}
    {{- $secretKey := $secret.data.password | b64dec }}
    {{ $secretKey }}
    {{- else }}
    {{ .Values.postgresql.password }}
    {{- end }}
