apiVersion: v1
kind: Secret
metadata:
  name: postgres-config
type: Opaque
stringData:
  PG_USER: |-
    {{- if .Values.postgresql.existingSecret.enabled }}
    {{- $secretName := .Values.postgresql.existingSecret.name }}
    {{- $userKey := .Values.postgresql.existingSecret.userKey }}
    {{- $secret := default (dict "data" (dict)) (lookup "v1" "Secret" "$secretName" "argo") }}
    {{- $secretkey := $secret.data.$userKey | b64dec }}
    {{ $secretKey }}
    {{- else }}
    {{ ###ZARF_VAR_PG_USER### }}
    {{- end }}
  PG_USER_PASSWORD: |-
    {{- if .Values.postgresql.existingSecret.enabled }}
    {{- $secretName := .Values.postgresql.existingSecret.name }}
    {{- $passwordKey := .Values.postgresql.existingSecret.passwordKey }}
    {{- $secret := default (dict "data" (dict)) (lookup "v1" "Secret" "$secretName" "argo") }}
    {{- $secretkey := $secret.data.$userKey | b64dec }}
    {{ $secretKey }}
    {{- else }}
    {{ ###ZARF_VAR_PG_USER_PASSWORD### }}
    {{- end }}
