apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: binding-controller
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: controller-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: controller-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: binding-server
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: argo-server
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: server-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: binding-workflow
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: argo-workflow
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: workflow-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: binding-default-server
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: server-view-only
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: view-server-role
  apiGroup: rbac.authorization.k8s.io
