apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.irsaRoleARN }}
    eks.amazonaws.com/audience: sts.amazonaws.com
  name: controller-account
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.irsaRoleARN }}
    eks.amazonaws.com/audience: sts.amazonaws.com
  name: argo-server
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.irsaRoleARN }}
    eks.amazonaws.com/audience: sts.amazonaws.com
  name: argo-workflow
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflow.service-account-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: argo-workflow
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-server.service-account-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: argo-server
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: controller-account.service-account-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: controller-account
type: kubernetes.io/service-account-token
