apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  namespace: argo-server
  name: allow-svc-a
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-server
  action: ALLOW
  rules:
  - to:
    - operation:
        methods: ["GET"]
        paths: ["/*"]
  - from:
    - source:
      principals:
        - "cluster.local/ns/argo/sa/wfapi"
        - "cluster.local/ns/argo/sa/argo-server"
        - "cluster.local/ns/argo/sa/controller-account"
      requestPrincipals:
        - "kubernetes/serviceaccount/system:serviceaccount:argo:wfapi"
        - "kubernetes/serviceaccount/system:serviceaccount:argo:argo-server"
    to:
    - operation:
      methods: ["POST", "PUT", "DELETE"]
      paths: ["/api/v1/*"]
