apiVersion: v1
kind: Secret
metadata:
  name: postgres-config
  namespace: "###ZARF_CONST_NAMESPACE###"
type: Opaque
stringData:
  PG_USER: "###ZARF_VAR_PG_USER###"
  PG_USER_PASSWORD: "###ZARF_VAR_PG_USER_PASSWORD###"
