apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "###ZARF_VAR_IRSA_ROLE_ARN###"
  name: controller-account
  namespace: "###ZARF_VAR_NAMESPACE###"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "###ZARF_VAR_IRSA_ROLE_ARN###"
  name: argo-server
  namespace: "###ZARF_VAR_NAMESPACE###"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow
  namespace: "###ZARF_VAR_NAMESPACE###"
