apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "###ZARF_VAR_IRSA_ROLE_ARN###"
  name: controller-account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "###ZARF_VAR_IRSA_ROLE_ARN###"
  name: argo-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow