apiVersion: v1
kind: Secret
metadata:
  name: argo-workflow.service-account-token
  namespace: "###ZARF_CONST_NAMESPACE###"
  annotations:
    kubernetes.io/service-account.name: argo-workflow
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-server.service-account-token
  namespace: "###ZARF_CONST_NAMESPACE###"
  annotations:
    kubernetes.io/service-account.name: argo-server
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: controller-account.service-account-token
  namespace: "###ZARF_CONST_NAMESPACE###"
  annotations:
    kubernetes.io/service-account.name: controller-account
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: controller-account.service-account-token
  namespace: "###ZARF_CONST_NAMESPACE###"
  annotations:
    kubernetes.io/service-account.name: argo-server-default
    namespace: "###ZARF_CONST_NAMESPACE###"
