apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "###ZARF_VAR_IRSA_ROLE_ARN###"
    eks.amazonaws.com/audience: sts.amazonaws.com
  name: controller-account
  namespace: "###ZARF_CONST_NAMESPACE###"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "###ZARF_VAR_IRSA_ROLE_ARN###"
    eks.amazonaws.com/audience: sts.amazonaws.com
  name: argo-server
  namespace: "###ZARF_CONST_NAMESPACE###"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "###ZARF_VAR_IRSA_ROLE_ARN###"
    eks.amazonaws.com/audience: sts.amazonaws.com
  name: argo-workflow
  namespace: "###ZARF_CONST_NAMESPACE###"
