apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: argo-package
  namespace: "###ZARF_CONST_NAMESPACE###"
spec:
  network:
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace
      - direction: Egress
        remoteGenerated: IntraNamespace
      - direction: Egress
        remoteGenerated: KubeAPI
      - direction: Ingress
        selector:
          app.kubernetes.io/name: argo-workflows-workflow-controller
        remoteGenerated: KubeAPI
      - direction: Ingress
        selector:
          app.kubernetes.io/name: argo-workflows-server
        remoteGenerated: KubeAPI
      #S3
      - direction: Egress
        ports:
          - ###ZARF_VAR_S3_PORT###