name: tag-push

on:
  push:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install UDS CLI
        shell: bash
        run: |
          set -a; source .env; set +a
          brew install defenseunicorns/tap/uds@${UDS_CLI_VERSION}

      - name: Build and publish the zarf package
        run: |
          uds zarf package create --confirm --flavor vanilla -a arm64 -o oci://${{env.REGISTRY}}/${{env.IMAGE_NAME}}
          uds zarf package create --confirm --flavor vanilla -a amd64 -o oci://${{env.REGISTRY}}/${{env.IMAGE_NAME}}
